### ISSUE TITLE
Warnings con -Wall

### ISSUE THREAD

**Issue by Federico77z** [EMoreschi/MocoLoco#11]
Start compiling using the -Wall option. I don't want to see any warning. Right now there are lots of them.

**Comment by EMoreschi** [comment]
All -Wall warning eliminated.
To eliminate all of them it was necessary to modify the twobit.c code from AndrelMartins.
We modified 3 variable types from uint32bit to int.
The commit of the work is attched here [https://github.com/EMoreschi/MocoLoco/commit/e30b85e0736a93db20e869367a0fe4c58b888f29](url)
