### ISSUE TITLE
Output: positional_occurrences

### ISSUE THREAD

**Issue by Federico77z** [EMoreschi/MocoLoco#14]
We'd need to split the count between Oligo and Oligo_RC. This will be useful also down the road.

Output must be tabular, with columns as follows:

Position Rank Oligo Num_Occ Oligo_RC Num_Occ_RC Tot_Occ PAL

Position: Position along the sequence
Rank: Rank of this motif
Oligo: Oligo
Num_Occ: Number of occurrences
Oligo_RC: RC_Oligo. 
Num_Occ_RC Number of occurrences RC. When Oligo is palindrome this number is equal to Num_Occ
PAL: Is palindrome? TRUE/FALSE
Tot_Occ: Num_Occ + Num_Occ_RC

**Comment by EMoreschi** [comment]
The output file was sorted as requested.
Here is an example of a possible output:

![Istantanea_2021-04-09_11-40-31](https://user-images.githubusercontent.com/77453569/114162429-60b33c00-9929-11eb-8683-34404335c855.jpg)
