### ISSUE TITLE
Output: Sum/Freq

### ISSUE THREAD

**Issue by Federico77z** [EMoreschi/MocoLoco#15]
Output must be tabular:

Pos Sum Freq

Keep it a tab separated table, do not use a column for labels like Positions: Freq: | and stuff like that... they make it difficult to import data in R and are completely useless.

**Comment by EMoreschi** [comment]
Output modified and now it is tabular.
This is an example of output file:

![Istantanea_2021-04-09_11-41-06](https://user-images.githubusercontent.com/77453569/114162320-48432180-9929-11eb-97e6-99985f106214.jpg)
