### ISSUE TITLE
Something strange with sums at the end of sequences

### ISSUE THREAD

**Issue by Federico77z** [EMoreschi/MocoLoco#16]
<img width="313" alt="Schermata 2021-04-06 alle 14 52 23" src="https://user-images.githubusercontent.com/36039850/113713559-c87a4480-96e7-11eb-9524-037f65fca006.png">

Something strange happens with sums towards the end of sequences.

**Comment by EMoreschi** [comment]
![Istantanea_2021-04-07_10-49-20](https://user-images.githubusercontent.com/77453569/113838750-5f4e0c00-978f-11eb-9660-c8f417f657f7.jpg)

Problem on the sum with different kmers solved. 
There was just a distraction error in different kmers sum vector, in which we cycled only on the first position.
