### ISSUE TITLE
New wobble feature for the random fasta generator

### ISSUE THREAD

**Issue by Federico77z** [EMoreschi/MocoLoco#17]
We need a new parameter, "wobble" for the "random fasta generator" that makes the position of implanted motifs change slightly.

For example, let's say we implant two motifs with 

-p 50,100

We can provide another parameter

-w 0,5

This means that while the first motif will always be implanted at position 50, the second motif will be implanted in a random position between 95 and 105.

The default for -w is 0 for all the matrices. The max value is 10.

**Comment by EMoreschi** [comment]
Enhancement of wobble parameters made. Now the tool can accept as input a -w<n1,n2,...,nN> parameter to ensure a random variability around implant positions (from p-w to p+w). Wobble values, if not inserted, are set to 0 as default.
The tool can not accept a -w value greater then 10. 
The tool provides also to check if all the possible implant positions randomly generated from -p and -w input parameters, for oligos coming from different jaspar matrices, don't overlap. Finally, if an overlap is found, the tool is able to distinguish if the overlap come from wrong implant positions or from wrong implant positions + wobble parameters.
