### ISSUE TITLE
Something strange with the frequencies

### ISSUE THREAD

**Issue by Federico77z** [EMoreschi/MocoLoco#19]
The frequencies of 6mers, 8mers and 10mers are always the same for the same position. Of course, this does not make sense.

<img width="642" alt="Schermata 2021-04-06 alle 16 46 41" src="https://user-images.githubusercontent.com/36039850/113730387-23b43300-96f8-11eb-9f6f-b44b60617812.png">
<img width="677" alt="Schermata 2021-04-06 alle 16 46 32" src="https://user-images.githubusercontent.com/36039850/113730399-257df680-96f8-11eb-9251-8650b030162e.png">

**Comment by pmandreoli** [comment]
solved  -> https://github.com/EMoreschi/MocoLoco/commit/8c3dab039ea9191aeed3cde9c68e5e209ebbb72b
- run with `-k 6,8,10`

![immagine](https://user-images.githubusercontent.com/33326058/113837742-704a4d80-978e-11eb-8ee0-84d701ce0d69.png)
