### ISSUE TITLE
Dev and master branches

### ISSUE THREAD

**Issue by Federico77z** [EMoreschi/MocoLoco#4]
It's perfectly fine to have a dev and master branches, but then you have to use them the right way. When you have finished a task and checked that it works in the dev then put the code in the master. Then move again to the dev for the next step or to tidy up your code. More importantly, I must always be able to pull the master branch and compile and test the code right away and it must compile. What happens in the dev branch is up to you.

**Comment by EMoreschi** [comment]
Merge done
